<?php

namespace Casa\Front2Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoGruppoRepository extends EntityRepository
{
}
