<?php

namespace Casa\Front2Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoRepository extends EntityRepository
{
}
